services:
  backend:
    build:
      context: ./backend
    expose:
      - "8080"
    depends_on:
      - database
    networks:
      - app-network
    restart: unless-stopped
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://database:5432/db
      SPRING_DATASOURCE_USERNAME: usr
      SPRING_DATASOURCE_PASSWORD: pwd

  database:
    build:
      context: ./Database
    expose:
      - "5432"
    environment:
      POSTGRES_DB: db
      POSTGRES_USER: usr
      POSTGRES_PASSWORD: pwd
    volumes:
      - db-data:/var/lib/postgresql/data
    networks:
      - app-network
    restart: unless-stopped

  httpd:
    build:
      context: ./http-server
    ports:
      - "80:80"
    depends_on:
      - backend
    networks:
      - app-network
    restart: unless-stopped

networks:
  app-network:

volumes:
  db-data:
