# Dockerfile
FROM httpd:2.4

# Copie ta page index.html dans le bon dossier
COPY index.html /usr/local/apache2/htdocs/

# Copie ta configuration Apache si besoin
COPY httpd.conf /usr/local/apache2/conf/httpd.conf
